[package]
name = "pancakes"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = { git = "https://github.com/hedonhermdev/rayon", branch = "partial-fold" }
csv = "*"
anyhow = "*"
